apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: wcs-keycloak-cone-connector
  name: wcs-keycloak-cone-connector
  namespace: wcs-keycloak-cone-connector
  annotations:
    iam.gke.io/gcp-service-account: wcs-keycloak-cone-connector@semi-wcs-dev.iam.gserviceaccount.com 