apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcs-keycloak-cone-connector
  namespace: wcs-keycloak-cone-connector
  labels:
    app: wcs-keycloak-cone-connector
    app.kubernetes.io/instance: wcs-keycloak-cone-connector
  annotations:
    workloads.cast.ai/max-replicas: '1'
    workloads.cast.ai/min-replicas: '1'
spec:
  replicas: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: wcs-keycloak-cone-connector
      app.kubernetes.io/managed-by: cloud-console
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: wcs-keycloak-cone-connector
        app.kubernetes.io/managed-by: cloud-console
      annotations:
        iam.gke.io/gcp-service-account: "wcs-keycloak-cone-connector@semi-wcs-dev.iam.gserviceaccount.com"
    spec:
      containers:
        - name: wcs-keycloak-cone-connector
          image: europe-docker.pkg.dev/semi-wcs-dev/keycloak-baton/baton-keycloak:latest
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              /app/baton-keycloak
              --provisioning
              --api_url="$KEYCLOAK_API_URL"
              --baton_client_id="$BATON_CLIENT_ID"
              --baton_client_secret="$BATON_CLIENT_SECRET"
              --keycloak_client_id="$KEYCLOAK_CLIENT_ID"
              --keycloak_client_secret="$KEYCLOAK_CLIENT_SECRET"
              --realm="$KEYCLOAK_REALM"
          envFrom:
            - secretRef:
                name: wcs-keycloak-cone-connector
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/secrets
              name: wcs-keycloak-cone-connector
              readOnly: true
      volumes:
        - name: wcs-keycloak-cone-connector
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: wcs-keycloak-cone-connector
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: "wcs-keycloak-cone-connector"
      terminationGracePeriodSeconds: 30
