apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    app: wcs-keycloak-cone-connector
  name: wcs-keycloak-cone-connector
  namespace: wcs-keycloak-cone-connector
spec:
  provider: gcp
  secretObjects:
  - secretName: wcs-keycloak-cone-connector
    type: Opaque
    data:
    - objectName: keycloak-baton-dev-master-api-url
      key: KEYCLOAK_API_URL
    - objectName: keycloak-baton-dev-master-baton_client_id
      key: BATON_CLIENT_ID
    - objectName: keycloak-baton-dev-master-baton_client_secret
      key: BATON_CLIENT_SECRET
    - objectName: keycloak-baton-dev-master-keycloak_client_id
      key: KEYCLOAK_CLIENT_ID
    - objectName: keycloak-baton-dev-master-keycloak_client_secret
      key: KEYCLOAK_CLIENT_SECRET
    - objectName: keycloak-baton-dev-master-realm
      key: KEYCLOAK_REALM
    - objectName: keycloak-baton-dev-master-client-secret
      key: CLIENT_SECRET
    - objectName: keycloak-baton-dev-master-client-id
      key: CLIENT_ID
  parameters:
    secrets: |
      - resourceName: "projects/semi-wcs-dev/secrets/keycloak-baton-dev-master-api-url/versions/latest"
        fileName: "keycloak-baton-dev-master-api-url"
      - resourceName: "projects/semi-wcs-dev/secrets/keycloak-baton-dev-master-baton_client_id/versions/latest"
        fileName: "keycloak-baton-dev-master-baton_client_id"
      - resourceName: "projects/semi-wcs-dev/secrets/keycloak-baton-dev-master-baton_client_secret/versions/latest"
        fileName: "keycloak-baton-dev-master-baton_client_secret"
      - resourceName: "projects/semi-wcs-dev/secrets/keycloak-baton-dev-master-keycloak_client_id/versions/latest"
        fileName: "keycloak-baton-dev-master-keycloak_client_id"
      - resourceName: "projects/semi-wcs-dev/secrets/keycloak-baton-dev-master-keycloak_client_secret/versions/latest"
        fileName: "keycloak-baton-dev-master-keycloak_client_secret"
      - resourceName: "projects/semi-wcs-dev/secrets/keycloak-baton-dev-master-realm/versions/latest"
        fileName: "keycloak-baton-dev-master-realm"
      - resourceName: "projects/semi-wcs-dev/secrets/keycloak-baton-dev-master-client-secret/versions/latest"
        fileName: "keycloak-baton-dev-master-client-secret"
      - resourceName: "projects/semi-wcs-dev/secrets/keycloak-baton-dev-master-client-id/versions/latest"
        fileName: "keycloak-baton-dev-master-client-id"
